# Default values for helm_chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  image: /alpine   # https://artifacts.trmc.osd.mil/ui/repos/tree/General/minerva-docker/ironbank/ubi/ubi8-minimal/8.5
  tag: 3.20.2
  appLabel: tilesets
  storageSize: 40Gi

tilesetsPVC:
  appLabel: tilesets-pv-claim
  tilesetsPV:
    storageClass: ""   # glusterfs-storage-minerva-retain
    pvcSize: 60Gi

#To be overridden
imagePullSecrets: neil-dockerhub-image-pull-secret
imagePullUrl: docker.io/library    # artifacts.trmc.osd.mil/minerva-docker
tilesetUrl: https://github.com/n2studio/python-fun/blob/master/fib.py
tilesetsDir: /tiled/tilesets
#ocpLoadBalancer: ocp-lb3.dev26.minerva.navy.mil
#externalProxy: security.dev26.minerva.navy.mil
