# Default values for helm_chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  image: ironbank/ironbank-nginx
  tag: 1.21.6
  appLabel: tilesets
  storageSize: 20Gi
  namespace: minerva-dev

tilesetsPVC:
  appLabel: tilesets-pv-claim
  tilesetsPV:
    pvName: tilesets-pv
    storageClass: glusterfs-storage-retain  #glusterfs-storage-minerva-retain
    pvcSize: 20Gi

#To be overridden
imagePullSecrets: artifacts.trmc.osd.mil-minerva-docker   #neil-dockerhub-image-pull-secret
#imagePullUrl: docker-registry.default.svc:5000/minerva-dev/  # docker.io/library/   
imagePullUrl: artifacts.trmc.osd.mil/minerva-docker/
tilesetUrl: http://www.n2studio.com/home/homeart1.jpg
tilesetsDir: /tiled/tilesets
#ocpLoadBalancer: ocp-lb3.dev26.minerva.navy.mil
#externalProxy: security.dev26.minerva.navy.mil
