apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.appLabel }}
  labels:
    app: {{ .Values.deployment.appLabel }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.deployment.appLabel }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.appLabel }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      initContainers:
        - name: download-tilesets
          image: {{ .Values.imagePullUrl }}{{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
          # proof of concept showing use of wget to copy data into the pvc mount
          command: ["sh", "-c", "uname -a; df -h; wget -P /tiled/tilesets http://www.n2studio.com/home/homeart1.jpg; ls -lah /tiled/tilesets/"]
          volumeMounts:
            - mountPath: /tiled/tilesets
              name: {{ .Values.deployment.appLabel }}-pv-storage
      containers:
        - env:   # The container below could be the lattice tiled container that just mounts the pvc that we wrote the file to above
          image: {{ .Values.imagePullUrl }}{{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
          imagePullPolicy: IfNotPresent
          name: {{ .Values.deployment.appLabel }}
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 2G
            requests:
              cpu: 200m
              memory: 500M
          volumeMounts:
            - mountPath: /tiled/tilesets
              name: {{ .Values.deployment.appLabel }}-pv-storage
            - mountPath: /tiled/config
              name: {{ .Release.Name }}-config
          # Using command will override the default commands in the container image
          # The 'tail -f dev/null' is to keep the container running otherwise it has nothing to do and stops
          command: ["sh", "-c", "uname -a; df -h; tail -f /dev/null;"]
      restartPolicy: Always
      volumes:
        - name: {{ .Values.deployment.appLabel }}-pv-storage
          persistentVolumeClaim:
            claimName: {{ .Values.tilesetsPVC.appLabel }}
        - name: {{ .Release.Name }}-config
          configMap:
            name: {{ .Release.Name }}-configmap