apiVersion: v1
kind: Secret
metadata:
  name: neil-dockerhub-image-pull-secret
  namespace: default
type:  kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    ew0KICAiYXV0aHMiOiB7DQogICAgImh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3Yx
    LyI6IHsNCiAgICAgICJ1c2VybmFtZSI6ICJuMnN0dWRpbyIsDQogICAgICAicGFz
    c3dvcmQiOiAiZGNrcl9wYXRfbVdfeU8tdUNsNWVnUWEyYzJhQnFRNFRaWXFNIg0K
    ICAgIH0NCiAgfQ0KfQ==