apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.appLabel }}
  labels:
    app: {{ .Values.deployment.appLabel }}
spec:
  selector:
    app: {{ .Values.deployment.appLabel }}
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080